name: Dummy Status Check

on:
  pull_request:
    branches:
      - dev

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy check
        run: echo "Status check passed!"
name: Dummy Status Check

on:
  pull_request:
    branches:
      - dev

jobs:
  dummy:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy check
        run: echo "Status check passed!"
